name: Test with Docker Image
inputs:
  CMAIZE_GITHUB_TOKEN:
    required: true
  integration_test:
    required: true

runs:
  using: "composite"
  steps:
    - name: Give Permission
      run: chmod +x ${GITHUB_ACTION_PATH}/test.sh 
      shell: bash 
    - name: Test Application
      env:
        CMAIZE_GITHUB_TOKEN: ${{inputs.CMAIZE_GITHUB_TOKEN}}
        int_test: ${{ inputs.integration_test }}
      run: ${GITHUB_ACTION_PATH}/test.sh
      shell: bash 
