# Send a repo dispatch to announce the update of the release image of a repo
name: send a release repo dispatch
inputs:
  repo_name:
    required: true
  DOCKER_PAT:
    required: true

runs:
  using: "composite"
  steps:
    - name: send a repo dispatch
      run: |
          repo=${{ inputs.repo_name }}
          low_name=${repo,,}
          curl -X POST https://api.github.com/repos/NWChemEx-CI-test/${repo}/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u "${DOCKER_PAT}" \
          -d '{"event_type": "utilities_release_update"}'
      shell: bash

#--data '{"event_type": "${low_name}_release_update", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'"  }}'
