name: send an update dispatch to target repos
inputs:
  to_repo:
    required: true
  type:
    required: true
  DOCKER_PAT:
    required: true
  from_repo:
    required: true
  initial_repo:
    required: true
  branch:
    required: false
    default: master

runs:
  using: "composite"
  steps:
    - name: send a repo dispatch
      run: |
        curl -X POST https://api.github.com/repos/NWChemEx-CI-test/${{inputs.to_repo}}/dispatches \
        -H 'Accept: application/vnd.github.everest-preview+json' \
        -H "Authorization: Bearer ${{ inputs.DOCKER_PAT }}" \
        -d '{"event_type": "${{ inputs.type }}", "client_payload": {"ref": "${{inputs.branch}}", "from_repo": "${{inputs.from_repo}}", "initial_repo": "${{inputs.initial_repo}}" } }'
      shell: bash

# -d '{"event_type": "${from_repo}_release_update"}'
# -u "${DOCKER_PAT}" \
#--data '{"event_type": "${low_name}_release_update", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'"  }}'
#repo=${{ inputs.from_repo }}
#low_name=${repo,,}
#echo ${{ inputs.to_repo }}
#repo=${{ inputs.to_repo }}
#echo ${repo}
