name: Build and Test
inputs:
  CPP_GITHUB_TOKEN:
    required: true
    type: string
runs:
  using: "composite"
  steps:
    - name: check name
      run: echo ${{inputs.CPP_GITHUB_TOKEN}}
      shell: bash
    - name: Give Permission
      run: chmod +x ${{github.action_path}}/build_and_test.sh 
      shell: bash 
    - name: Build Documentation
      run: ${{github.action_path}}/build_and_test.sh
      shell: bash 