name: Build and Test
inputs:
  CPP_GITHUB_TOKEN:
    description: CPP Github Token
    required: true
runs:
  using: "composite"
  steps:
    - name: Give Permission
      run: chmod +x ${{github.action_path}}/build_and_test.sh 
      shell: bash 
    - name: Build Documentation
      run: ${{github.action_path}}/build_and_test.sh
      shell: bash 