name: Test Documentation
inputs:
  target:
    type: string
  skip_doxygen:
    type: boolean
runs:
  using: "composite"
  steps:
    - name: Give Permission to build_docs.sh
      run: chmod +x ${GITHUB_ACTION_PATH}/build_docs.sh 
      shell: bash 
    - name: Build Documentation
      if: ${{ inputs.skip_doxygen == 'false' }} 
      run: ${GITHUB_ACTION_PATH}/build_docs.sh ${{inputs.target}}
      shell: bash
    - name: Give Permission to build_sphinx_docs.sh
      run: chmod +x ${GITHUB_ACTION_PATH}/build_sphinx_docs.sh 
      shell: bash
    - name: Build Sphinx Documentation
      run: ${GITHUB_ACTION_PATH}/build_sphinx_docs.sh
      shell: bash
