name: Test Documentation
inputs:
  target:
    required: true
    type: string
runs:
  using: "composite"
  steps:
    - name: Give Permission
      run: chmod +x ${{github.action_path}}/build_docs.sh 
      shell: bash 
    - name: Build Documentation
      run: ${{github.action_path}}/build_docs.sh ${{inputs.target}}
      shell: bash