name: Test Documentation
inputs:
  target:
    type: string
  skip_doxygen:
    type: boolean
runs:
  using: "composite"
  steps:
    - name: Give Permission to build_docs.sh
      run: chmod +x ${{github.action_path}}/build_docs.sh 
      shell: bash 
    - name: Build Documentation
      # if: ${{ inputs.skip_doxygen != true }} ${{github.action_path}}/build_docs.sh ${{inputs.target}}
      run: echo 'this is skip_doxygen = ' ${{ inputs.skip_doxygen }}
      shell: bash
    # - name: Give Permission to build_sphinx_docs.sh
    #   run: chmod +x ${{github.action_path}}/build_sphinx_docs.sh 
    #   shell: bash
    # - name: Build Sphinx Documentation
    #   run: ${{github.action_path}}/build_sphinx_docs.sh
    #   shell: bash