name: Test Documentation
inputs:
  target:
    type: string
runs:
  using: "composite"
  steps:
    - name: Give Permission to build_docs.sh
      run: chmod +x ${{github.action_path}}/build_docs.sh 
      shell: bash 
    - name: Build Documentation
      if: ${{ github.event.repository.name != '.github'}}
      run: ${{github.action_path}}/build_docs.sh ${{inputs.target}}
      shell: bash
    - name: Give Permission to build_sphinx_docs.sh
      run: chmod +x ${{github.action_path}}/build_sphinx_docs.sh 
      shell: bash
    - name: Build Sphinx Documentation
      run: ${{github.action_path}}/build_sphinx_docs.sh
      shell: bash