name: Base image gcc

on:
  workflow_call:
  workflow_dispatch:
  inputs:
    cmake_version:
      type: string
      required: false
      default: 3.17.0
    gcc_version:
      type: string
      required: false
      default: 9

jobs:
  image-with-gcc:
    runs-on: ubuntu:latest
    steps:
      - uses: actions/checkout@v3
      - name: Build image
        run: |
          docker load -i /tmp/base-gcc.tar
          docker build -t base-cmake:latest -f Dockerfile/base-cmake.Dockerfile . --build-arg GCC_VERSION=${{inputs.gcc_version}} --build-arg CMAKE_VERSION=${{cmake.ubuntu_version}}
          docker save -o /tmp/base-cmake.tar base-cmake:latest
