name: Base image gcc cmake

on:
  workflow_dispatch:
    inputs:
      cmake_version:
        type: string
        required: false
        default: 3.17.0
      gcc_version:
        type: string
        required: false
        default: 9
      ubuntu_version:
        type: string
        required: false
        default: 20.04

jobs:
  image-with-cmake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: NWChemEx-CI-test/.github/actions/base_image_gcc@master
        with:
          gcc_version: ${{ inputs.gcc_version }}
          ubuntu_version: ${{ inputs.ubuntu_version }}
      - name: Build image
        run: |
          docker build -t ghcr.io/nwchemex-ci-test/base-gcc-cmake:latest -f Dockerfile/base-cmake.Dockerfile . --build-arg GCC_VERSION=${{inputs.gcc_version}} --build-arg CMAKE_VERSION=${{inputs.cmake_version}}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_PAT }}
      - name: Push the image
        run: |
          docker push ghcr.io/nwchemex-ci-test/base-gcc-cmake:latest
