name: Base image gcc cmake

on:
  workflow_call:
    inputs:
      cmake_version:
        type: string
        required: true
      gcc_version:
        type: string
        required: true
      clang_version:
        type: string
        required: true
      ubuntu_version:
        type: string
        required: true

jobs:
  image-with-cmake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: NWChemEx-CI-test/.github
      - name: Install gcc and clang
        uses: NWChemEx-CI-test/.github/actions/install_one@master
        with:
          gcc_version: ${{ inputs.gcc_version }}
          clang_version: ${{ inputs.clang_version }}
          ubuntu_version: ${{ inputs.ubuntu_version }}
          package_name: gcc-clang
          parent_image_name: " "
      - name: Install cmake
        uses: NWChemEx-CI-test/.github/actions/install_one@master
        with:
          cmake_version: ${{ inputs.cmake_version }}
          package_name: cmake
          parent_image_name: gcc-clang
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_PAT }}
      - name: Push the image
        uses: NWChemEx-CI-test/.github/actions/push_image@master
        with:
          tmp_image_name: base-cmake
          tmp_image_tag: latest
          image_name: ghcr.io/nwchemex-ci-test/base-cmake
          image_tag: latest
