name: Build and Deploy Documentation
on:
  push:
    branches:
      - master
      # - reuseable-workflow

jobs:
  Build-Documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Obtain Source
        uses: actions/checkout@v2
      - name: Get dependencies
        env:
          cmake_version: 3.16.3
        uses: NWChemEx-Project/.github/actions/get_dependencies@master
        with:
          dependencies: sphinx
      - name: Build documentation
        run: |
          . venv/bin/activate
          cd docs
          make html
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          # personal_token: ${{ secrets.CREATE_PULL_REQUEST_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html
