name: C_C++_CI with Docker Image

on:
  workflow_call:
    inputs:
      repo:
        required: true
        type: string
      clang-build:
        required: true
        type: boolean
      gcc-build:
        required: true
        type: boolean
      ninja_build:
        required: true
        type: boolean
    secrets:
      CMAIZE_GITHUB_TOKEN:
        required: true
      CONTAINER_REPO_TOKEN:
        required: true

jobs:
  Build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/yzhang-23/build_${{inputs.repo}}:v1
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.DOCKER_PAT }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Build using Clang
        if: ${{inputs.clang-build == true}}
        env:
          cmake_version: ${{ matrix.cmake_version }}
          clang_version: ${{ matrix.clang_version }}
          ninja_build: ${{ inputs.ninja_build }}
        uses: yzhang-23/.github/actions/image-build@master
        with: 
          CMAIZE_GITHUB_TOKEN: ${{ secrets.CMAIZE_GITHUB_TOKEN }}
      - name: Build using GCC
        if: ${{inputs.gcc-build == true}}
        env:
          cmake_version: ${{ matrix.cmake_version }}
          gcc_version: ${{ matrix.gcc_version }}
          ninja_build: ${{ inputs.ninja_build }}
        uses: yzhang-23/.github/actions/image-build@master
        with: 
          CMAIZE_GITHUB_TOKEN: ${{ secrets.CMAIZE_GITHUB_TOKEN }}
      - name: Test Application
        uses: yzhang-23/.github/actions/image-test@master
        with: 
          CMAIZE_GITHUB_TOKEN: ${{ secrets.CMAIZE_GITHUB_TOKEN }}
