name: Test Documentation
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - reuseable-workflow

jobs:
  Build-Documentation:
    uses: NWChemEx-Project/.github/.github/workflows/test_docs_tmpl.yml@reuseable-workflow
    with:
      dependencies: sphinx
      skip_doxygen: true
