name: Test Documentation
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - doc-generation

jobs:
  Build-Documentation:
    uses: NWChemEx-Project/.github/.github/workflows/test_docs_tmpl.yml@master
    with:
      dependencies: sphinx
      skip_doxygen: true
